env:
  DEPLOY_PATH: ''
  SSH_DOMAIN: ''
  SSH_USER: ''
name: Deploy to prod
"on":
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: "Say your name! 🤖"
jobs:
  deploy:
    name: Build and deploy app
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    environment:
      name: prod
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Build
        run: yarn build

      - name: Create SSH key
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ env.SSH_DOMAIN }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_ed25519
          chmod 600 /home/runner/.ssh/id_ed25519
          eval `ssh-agent -s`
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          ssh-add /home/runner/.ssh/id_ed25519

      - name: Deploy
        run: rsync -avz ./dist/* ${{ env.SSH_USER }}@${{ env.SSH_DOMAIN }}:${{ env.DEPLOY_PATH }}
